# Generated by Django 2.0.6 on 2018-06-13 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reg',
            fields=[
                ('user', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=20)),
                ('fname', models.CharField(max_length=40)),
                ('lname', models.CharField(max_length=40)),
                ('dob', models.DateField()),
                ('mobno', models.IntegerField()),
            ],
        ),
    ]
